export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            padding: "1rem",
            backgroundColor: "#F5DAD2",
          }}
        >
          <h3>This is header</h3>
        </header>
        <main>{children}</main>
        <footer
          style={{
            padding: "1rem",
            backgroundColor: "#FCFFE0",
          }}
        >
          <h3>This is footer</h3>
        </footer>
      </body>
    </html>
  );
}
